/*DDL*/

CREATE DATABASE M_InLock;
USE M_InLock;

CREATE TABLE Usuarios(
UsuarioId INT PRIMARY KEY IDENTITY
,Email VARCHAR(128) UNIQUE NOT NULL
,Senha VARCHAR(128) NOT NULL
,Permissao CHAR(1) DEFAULT('C')
);

CREATE TABLE Paises(
PaisId INT PRIMARY KEY IDENTITY
,NomePais VARCHAR(128) NOT NULL
)

CREATE TABLE Estudios(
EstudioId INT PRIMARY KEY IDENTITY
,NomeEstudio VARCHAR(128) NOT NULL
,PaisId INT FOREIGN KEY REFERENCES Paises(PaisId)
,DataCriacao DATE NOT NULL
,UsuarioId INT FOREIGN KEY REFERENCES Usuarios(UsuarioId)
);

CREATE TABLE Jogos(
JogoId INT PRIMARY KEY IDENTITY
,NomeJogo VARCHAR(128) NOT NULL
,Descricao TEXT NOT NULL
,DataLancamento DATE NOT NULL
,Valor FLOAT NOT NULL
,EstudioId INT FOREIGN KEY REFERENCES Estudios(EstudioId)
);
